---
deployment:
  tasks:
    - cp -r . /home/csgocomp/src/
    - nvm use 16
    - cd /home/csgocomp/src && npm install
    - cd /home/csgocomp/src && pkill -f "node" || true
    - cd /home/csgocomp/src && npm run start &